org.slf4j.simpleLogger.logFile=logger.txt
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=true
org.slf4j.simpleLogger.showShortLogName=true
# Output in format: [LEVEL] [Time] [Message] ([LoggerName])
org.slf4j.simpleLogger.levelInBrackets=true
